Optimisations file manager
leav-solutions/leav-engine pull request #209
Opened 2023-02-20 14:07 UTC by Jerome-Millot

2023-02-20 16:40 UTC, TdyP requested changes

2023-02-20 16:40 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileSystem.ts
> +import { ITreeRepo } from 'infra/tree/treeRepo';
Il ne doit pas y avoir d'espace à la fin et au début dans les `{}`
eslint aurait dû normalement le corriger en pre-commit

2023-02-20 16:40 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileUtilsHelper.ts
> +    const queryParts = [aql`FOR r in ${coll}`];
On est dans la couche domain ici, il ne doit pas y avoir de requêtes directes.
Si besoin d'avoir une requête spécifique optimisée, il vaut mieux passer par la couche infra

2023-02-20 16:40 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileUtilsHelper.ts
> +    const query = aql`FOR r in ${coll} FILTER (r.${FilesAttributes.FILE_NAME} == ${parentName} AND r.${FilesAttributes.FILE_PATH} == ${join(...parentPath)}) RETURN MERGE(r, {library: ${library}})`;
Même remarque qu'au dessus

2023-02-21 08:36 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileSystem/handleMoveEvent.ts
> +            await deps.treeRepo.moveElement({
Est-ce que tu as mesuré le gain en passant par le repo direct plutôt que le domain? Il y a pas mal de choses dans le domain qui sont récupérées depuis le cache sans interroger arango, je ne sais pas si le coût est si important.
Ça pose probléme parce qu'en plus de checker les permissions, on fait quelques trucs annexes, comme envoyer un événements "move element" qui permet de mettre à jour le front et permettra d'alimenter les logs également. En appelant le repo directement ces choses là ne sont pas faites.

2023-02-21 08:40 UTC, Jerome-Millot commented on apps/core/src/domain/filesManager/helpers/handleFileSystem/handleMoveEvent.ts
> +            await deps.treeRepo.moveElement({
oui, c'est environ 2x plus rapide, par contre j'ai effectivement raté cette partie évènements, je regarde ça.

2023-02-21 08:43 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileSystem/handleUpdateEvent.ts
> +    updateRecordFile(recordData, record.id, library, deps, ctx);
En enlevant simplement ces `await`, les exceptions ne sont plus catchées du coup et on a donc des  `Unhandled Rejection`

2023-02-23 08:49 UTC, TdyP requested changes

2023-02-23 08:49 UTC, TdyP commented on apps/core/src/domain/tree/treeDomain.ts
> +        },
Plutôt que dupliquer la fonction et donc devoir en maintenir 2 dans le futur, ne pourrait-on pas utiliser `moveElement` en rajoutant juste un paramètre `skipChecks` (à `false` par défaut) ?

2023-02-23 08:49 UTC, TdyP commented on apps/core/src/domain/filesManager/helpers/handleFileSystem/handleUpdateEvent.ts
> +        throw e;
Pour moi ça ne corrige pas le problème, on a toujours une `Unhandled rejection`
Quel est le gain en supprimant le `await` sur cet appel et `requestPreviewGeneration` ?

2023-02-23 08:49 UTC, TdyP commented on apps/core/src/infra/filesManager/filesManager.ts
> +// Copyright LEAV Solutions 2017
Pour être raccord avec les ficheirs existants, il faudrait appeler celui-là `filesManagerRepo`.
Ça serait bien d'avoir quelques tests unitaires aussi, surtout que `getRecord` gère plusieurs cas selon les paramètres

2023-02-23 08:49 UTC, TdyP commented on apps/core/src/infra/filesManager/filesManager.ts
> +                    `[FilesManager] Multiple record find using fileName and filePath: ${recordsFind.list.toString()}`
f**ou**nd

2023-03-03 11:03 UTC, TdyP approved these changes

2023-03-03 11:03 UTC, merged