Fix views
leav-solutions/leav-engine pull request #212
Opened 2023-02-21 14:36 UTC by jrmyb

https://unisson.aristid.com/browse/LEAV-539
https://unisson.aristid.com/browse/LEAV-392

+ update order views on duplicate, delete, ...

2023-02-21 15:37 UTC, TdyP requested changes

2023-02-21 15:37 UTC, TdyP commented on apps/core/src/domain/view/viewDomain.ts
> +export const PREFIX_USER_VIEWS_ORDER = 'user_views_order_';
Pourquoi cette constante est définie coté back?

2023-02-21 15:37 UTC, TdyP commented on apps/data-studio/src/components/LibraryItemsList/ViewPanel/ViewPanel.tsx
>          return (
Je sais que c'est du vieux code, mais on pourrait appeler le composant `Loading` ici plutôt que le `Spin` "en dur"

2023-02-21 15:37 UTC, TdyP commented on apps/data-studio/src/graphQL/mutations/views/hooks/useAddViewMutation.ts
> +                    const list = options.variables.view.id
Si c'est un update et si on renvoie bien l'ID de la vue dans la mutation, Apollo arrivera à faire la mise à jour tout seul.
Il y a que dans le cas d'un ajout où il faut effectivement l'ajouter à la liste à la main

2023-02-21 15:37 UTC, TdyP commented on apps/data-studio/src/graphQL/mutations/views/hooks/useDeleteViewMutation.ts
> +    PREFIX_SHARED_VIEWS_ORDER_KEY,
Pas utilisé ?

2023-02-21 15:56 UTC, TdyP commented
Erreur si on sauvegarde la vue alors qu'on a encore jamais affiché la liste complète des vues (donc pas appeler `getViewsListQuery`): `Error: cacheData is null`

2023-02-21 15:57 UTC, jrmyb commented on apps/data-studio/src/graphQL/mutations/views/hooks/useAddViewMutation.ts
> +                    const list = options.variables.view.id
On renvoie bien l'ID de la vue mais non la liste ne se mettait pas à jour sur un _save_

2023-02-21 16:05 UTC, TdyP commented on apps/data-studio/src/graphQL/mutations/views/hooks/useAddViewMutation.ts
> +                    const list = options.variables.view.id
ok
D'habitude ça le fait mais peut-être que si on a une fonction `update`, ça zappe la mise à jour auto d'Apollo

2023-02-23 09:28 UTC, TdyP approved these changes

2023-02-23 09:28 UTC, merged