Xstream 14 add error message list action
leav-solutions/leav-engine pull request #307
Opened 2023-08-25 07:40 UTC by Kekelgrs

2023-08-31 09:58 UTC, TdyP requested changes

2023-08-31 09:58 UTC, TdyP commented on apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCCard/ActionContent/CustomMessage/CustomMessage.tsx
> +    custom_message: string;
Les noms de props sont plutôt en camelCase normalement

2023-08-31 09:58 UTC, TdyP commented on apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCCard/ActionContent/CustomMessage/CustomMessage.tsx
> +    changeCustomMessage?: (actionId: number, value: string, lang: string) => void;
Par convention, les props qui sont des fonctions de callback commencent par `on`. Ce qui donnerait ici `onChangeCustomMessage`

2023-08-31 09:58 UTC, TdyP commented on apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCCard/ActionContent/CustomMessage/CustomMessage.tsx
> +    return <div>{<>{_getRenderedElement()}</>}</div>;
Pourquoi ne pas return directement ton `Input` ici? A-t-on besoin de ces `div` autour ?

2023-08-31 09:58 UTC, TdyP commented on apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCContainer/ALCContainer.tsx
> +    const changeCustomMessage = (actionId: number, value: string, lang: string) => {
Par convention, les fonctions "privés" commencent par un `_`. 
Aussi, c'est plus clair si la fonction qui sera passée en props commence par `_handle` => `_handleCustomMessage`

2023-08-31 09:58 UTC, TdyP commented on apps/admin/src/components/attributes/EditAttribute/EditAttributeTabs/ActionsListTab/ALCList/ALCList.tsx
> +    changeCustomMessage?: (actionId: number, value: string, lang: string) => void;
Même remarque sur le nom de la fonction

2023-08-31 09:58 UTC, TdyP commented on apps/core/src/domain/actionsList/actionsListDomain.ts
> +                        {[ctx.attribute.id]: ''},
Pourquoi mettre l'erreur à vide ici? C'est bien là que le `customMessage` nous intéresse

2023-08-31 10:12 UTC, Kekelgrs commented on apps/core/src/domain/actionsList/actionsListDomain.ts
> +                        {[ctx.attribute.id]: ''},
SI l'erreur est a vide, alors on surcharger le message de l'erreur avec le message envoyé au deuxième param.

2023-09-01 07:40 UTC, TdyP approved these changes

2023-09-07 07:46 UTC, TdyP commented on apps/core/src/domain/actionsList/actionsListDomain.ts
>                              : '';
ce double ternaire devient un peu compliqué à lire je trouve. Il pourrait être un peu allégé au niveau syntaxe:
```
let customMessage = action?.error_message?.[ctx.lang]?.trim() ??  action?.error_message?.[ctx.defaultLang]?.trim() ?? '';
```

2023-09-07 12:15 UTC, TdyP approved these changes

2023-09-07 12:16 UTC, merged