[Core] Import data/config: add versions, trees
leav-solutions/leav-engine pull request #366
Opened 2023-12-07 13:10 UTC by stevenfreville

2023-12-07 14:51 UTC, TdyP requested changes

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/_types/import.ts
> +    versions?: IImportValueVersion[];
```suggestion
    version?: IImportValueVersion[];
```

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/attribute/attributeDomain.ts
> +            // TODO: Too many events are sent, after an importConfig, core loads up to 100% for 10mins
Commentaire à supprimer, car rien à corriger

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/eventsManager/eventsManagerDomain.ts
> +        pubSubEvent.instanceId = config.instanceId;
Il ne faut pas ajouter `instanceId` quand on dépile les messages mais plutôt dans la fonction `_send` qui envoie les messages. Ce correctif est fait dans une autre PR, pas encore mergée

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/import/importDomain.ts
> +    ): Promise<any> => {
Dans la mesure du possible, on évite de mettre des `any` volontairement. Ici, on peut même laisser Typescript inférer le type de retour, pas besoin de lui précisier.

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/import/importDomain.ts
> +                    // progress.elementsNb += element.matches.length + element.data.length;
A nettoyer

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/import/importDomain.ts
> +        isCacheActive = false
6 arguments ça commence à faire pas mal et `ctx` est, par convention, toujours le dernier argument.
On pourrait passer par un objet d'arguments?

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/import/importDomain.ts
> +                    await _updateTaskProgress(nbData, 'tasks.import_description.elements_process');
`'tasks.import_description.elements_process'` correspond à une entrée dans les fichiers de traduction. 

Si on la modifie ici, il faut penser à mettre à jours les fichiers de traduction du core également (dans `apps/core/src/locales`)

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/domain/value/helpers/validateValue.ts
> +        if (!isPresent && value.version[treeName] !== null) {
Pour optimiser un peu, on pourrait tester la condition `value.version[treeName] !== null` avant l'appel à `isNodePresent`

2023-12-07 14:51 UTC, TdyP commented on apps/core/src/utils/utils.ts
> +      if (typeof error === 'undefined')
On met toujours les `{}` autour d'un `if`

Norlament eslint ou prettier auraient dû le corriger automatiquement

2023-12-07 15:00 UTC, stevenfreville commented on apps/core/src/domain/import/import-data-schema.json
> +        "element": {
Oui en effet on avait discuté, j'ai oublié de mettre le schéma à jour mais le fichier des data l'est. JSON Schema validation ne renvoi pas d'erreur si on ajoute un attribut qui n'est pas définit pour information.

2023-12-07 15:05 UTC, stevenfreville commented on apps/core/src/domain/import/importDomain.ts
> +                    await _updateTaskProgress(nbData, 'tasks.import_description.elements_process');
tasks.import_description.elements_process est dèjà définit. Elle n'est pas modifié dans ce code, juste utilisée.
![image](https://github.com/leav-solutions/leav-engine/assets/11257218/4761acd5-d4c7-4302-bd1d-8a9252b5f11b)

2023-12-08 11:18 UTC, TdyP approved these changes

2023-12-08 14:43 UTC, jrmyb requested changes

2023-12-08 14:43 UTC, jrmyb commented on apps/core/src/domain/import/importDomain.ts
> +        const filters: Array<IMatch & { operator: Operator }> = matches.reduce(
prettier?

2023-12-08 14:44 UTC, jrmyb commented on apps/core/src/domain/import/importDomain.ts
>                          await cacheService.getCache(ECacheType.DISK).storeData({
On met déjà en cache dans treatValue. Il faudrait faire l'un ou l'autre mais aussi ne pas mettre tous l'élément en cache mais seulement les attributs liens et versionables.

2023-12-20 13:27 UTC, jrmyb commented on apps/core/src/domain/import/importDomain.ts
> +                            (stats as IStat).links += 1;
Cette statistique n'est plus correcte

2024-01-02 14:28 UTC, AdilAristid approved these changes

2024-01-10 12:59 UTC, jrmyb approved these changes

2024-01-10 14:17 UTC, merged