Import data upgrade from op
leav-solutions/leav-engine pull request #379
Opened 2024-01-12 11:11 UTC by stevenfreville

2024-01-12 14:36 UTC, TdyP requested changes

2024-01-12 14:36 UTC, TdyP commented on apps/core/src/interface/cli.ts
> +                    await importApp.importData(filepath);
Étant donné que l'import est fait par un worker par la suite, le fichier à importer doit obligatoirement être dans le dossier des fichiers à importer (défini dans `config.import.directory`). Il faudrait peut-être le déplacer à ce moment là?

2024-01-12 14:36 UTC, TdyP commented on apps/core/src/app/core/importApp.ts
> +                await graphqlApp.getSchema();
Cet appel n'est pas nécessaire. D'ailleurs, celui dans `importConfig` juste au dessus ne l'est pas non plus

2024-01-12 15:06 UTC, stevenfreville commented on apps/core/src/interface/cli.ts
> +                    await importApp.importData(filepath);
Oui effectivement, on va avoir des problèmes de path durant l'import sinon

2024-01-12 15:06 UTC, stevenfreville commented on apps/core/src/app/core/importApp.ts
> +                await graphqlApp.getSchema();
très bien, je les enlève

2024-01-15 08:25 UTC, TdyP approved these changes

2024-01-15 08:25 UTC, merged

2024-01-15 08:32 UTC, jrmyb approved these changes