xstream-409 [fix] Data studio crash if campaign have broadcast dates
leav-solutions/leav-engine pull request #388
Opened 2024-02-12 16:14 UTC by fatb38

2024-02-13 08:18 UTC, philippechevieux commented on apps/core/src/domain/record/recordDomain.ts
> +    translator?: i18n;
De la même manière que l'on à `core.utils`, est-ce qu'il ne faudrait pas avoir `core.translator` ?

2024-02-13 09:22 UTC, renaudAmsellem commented
Possibilité d'ajouter un test ?

2024-02-13 09:51 UTC, fatb38 commented on apps/core/src/domain/record/recordDomain.ts
> +    translator?: i18n;
J'ai pris un exemple existant dans leav, `core.translator` n'existe pas

2024-02-13 09:59 UTC, TdyP commented on apps/core/src/domain/record/recordDomain.ts
> +    translator?: i18n;
Effectivement, il y a quelques trucs transverses disponibles dans l'injecteur de dépendance et qui ne sont pas préfixés: `config`, `translator`, ... 
Je suis d'accord qu'il y a une petite incohérence avec `core.utils` qui lui est préfixé. 
On pourrait éventuellement remettre de la cohérence dans tout ça, mais je ne suis pas sur qu'il fasse le faire dans cette PR, ça me semble pas très problématique

2024-02-13 10:01 UTC, TdyP commented on apps/core/src/domain/record/recordDomain.ts
> +            } else if (subLabelAttributeProps.format === AttributeFormats.DATE_RANGE && subLabelValues?.[0].value !== null) {
On a du `===` ou `!==` de partout et on a doit avoir une règle eslint qui le vérifie.

2024-02-13 10:02 UTC, TdyP commented
Il faudrait faire la même dans la fonction `_getLabel` également, si jamais on met un attribut au format période dans le libellé de la carte d'identité.

2024-02-13 10:03 UTC, TdyP requested changes
Il faudrait faire la même dans la fonction _getLabel également, si jamais on met un attribut au format période dans le libellé de la carte d'identité.

2024-02-13 17:29 UTC, fatb38 commented on apps/core/src/domain/record/recordDomain.ts
> +            } else if (subLabelAttributeProps.format === AttributeFormats.DATE_RANGE && subLabelValues?.[0].value !== null) {
corrigé

2024-02-14 12:56 UTC, renaudAmsellem commented on apps/core/src/domain/record/recordDomain.spec.ts
> +                            ...mockStandardValue,
C'est étrange ces différences d'espacements non ? Il n'y a pas un problème de config prettier ?

2024-02-14 12:58 UTC, renaudAmsellem approved these changes

2024-02-14 13:17 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.spec.ts
> -        test('Should delete an record and return deleted record', async function () {
C'est un problème de prettier cet espace ?

2024-02-14 13:31 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.spec.ts
> +                    expect(res).not.toBe(null);
Tu peux utiliser toBeNull()
https://jestjs.io/fr/docs/expect#tobenull

2024-02-14 13:31 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.spec.ts
> +                    expect(res.subLabel).toBe(null);
idem

2024-02-14 13:33 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.ts
> +            const value: IValue['value'] | undefined = labelValues.pop().value;
C'est pas plus safe de faire `labelValues?.[0]?.value`

2024-02-14 13:35 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.ts
> +            const value: IValue['value'] | undefined = subLabelValues.pop().value;
idem

2024-02-14 13:35 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.ts
> +                subLabel = value !== null ? _convertDateRangeToString(value, ctx) : value;
```suggestion
                subLabel = value !== null ? _convertDateRangeToString(value, ctx) : null;
```

2024-02-14 13:36 UTC, Delmotte-Vincent commented on apps/core/src/domain/record/recordDomain.ts
> +    };
tu peux extraire lang car tu l'utilises 3 fois

2024-02-14 14:22 UTC, fatb38 commented on apps/core/src/domain/record/recordDomain.spec.ts
> -        test('Should delete an record and return deleted record', async function () {
oui j'utilise la config prettier et il enleve les espace. D'ailleurs aucun fichier n'est formaté avec prettier, tente un coup tu vas te prendre qq modifs 😅

2024-02-14 14:22 UTC, fatb38 commented on apps/core/src/domain/record/recordDomain.spec.ts
> +                            ...mockStandardValue,
oui j'ai utilisé prettier pour ce fichier, le soucis est qu'aucun fichier n'y formaté avec, on devrait ouvrir une autre PR de formatage avec prettier et ajouter le script au pre commit

2024-02-14 14:31 UTC, P0ppoff commented on apps/core/src/domain/record/recordDomain.spec.ts
> +                    expect(res).not.toBe(null);
Est ce que tu trouves ça plus lisible ? 

Pour ma part je ne trouve pas. J'aime la syntaxe utilisé par Arnaud car elle permet plus facilement de faire une évolution. De plus je trouve que l'erreur est plus parlante quand le test ne passe pas.

2024-02-14 14:35 UTC, P0ppoff approved these changes

2024-02-15 14:52 UTC, merged