feat(@leav/ui): add refresh and success notification on new element c…
leav-solutions/leav-engine pull request #398
Opened 2024-02-21 15:12 UTC by P0ppoff

…reation inside library

2024-02-21 15:53 UTC, TdyP requested changes

2024-02-21 15:53 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/MenuItemList/MenuItemList.test.tsx
> +        it.each([LibraryBehavior.standard, LibraryBehavior.files, LibraryBehavior.directories])(
on utilise `test` plutôt que `it` dans LEAV. Je n'ai rien contre `it` personnellement, simple question de cohérence

2024-02-21 15:53 UTC, TdyP commented on libs/ui/src/locales/en/shared.json
> +            "description": "The view have been refreshed and now includes the new element."
Je ne pense pas qu'il faille dire que la vue inclut le nouvel élément, car elle peut justement ne pas l'inclure, en fonction des filtres actifs. Pour moi, pas besoin d'autre chose que "élément créé avec succès"

2024-02-21 16:02 UTC, P0ppoff commented on libs/ui/src/locales/en/shared.json
> +            "description": "The view have been refreshed and now includes the new element."
D'après le DS je suis obligé de mettre une description, je peux la mettre vide mais c'est bof, tu as une idée ?

2024-02-21 16:16 UTC, P0ppoff commented on libs/ui/src/locales/en/shared.json
> +            "description": "The view have been refreshed and now includes the new element."
Je viens de voir avec Seb, on va mettre une description vide 

<img width="1281" alt="Capture d’écran 2024-02-21 à 17 13 49" src="https://github.com/leav-solutions/leav-engine/assets/10043818/af16ad9d-9bc6-4498-8925-07bed071f823">

2024-02-22 08:15 UTC, TdyP approved these changes

2024-02-22 08:15 UTC, merged