fix(@leav/ui): Improve EditRecordPage css
leav-solutions/leav-engine pull request #422
Opened 2024-03-12 13:49 UTC by philippechevieux

2024-03-12 16:45 UTC, TdyP approved these changes

2024-03-14 14:04 UTC, P0ppoff requested changes

2024-03-14 14:04 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.test.tsx
>          expect(screen.getByRole('button', {name: /submit/})).toBeInTheDocument();
**typo (blocking):** Il est passé où le bouton `cancel` ? je pense que l'on teste plus la même chose, et surtout on a deux lignes consécutives qui testent la même chose

2024-03-14 14:04 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.test.tsx
> +                title={customTitle}
**suggestion:** J'aurai inliné le titre. Il ne sert à rien de le sortir

2024-03-14 14:04 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.test.tsx
> +    test('Should hide refresh button', async () => {
**suggestion:** 
```suggestion
    test('Should hide refresh button on props', async () => {
```

2024-03-14 15:31 UTC, renaudAmsellem approved these changes

2024-03-14 15:31 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecord/EditRecord.tsx
> +    padding-right: 24px;
**nitpick (if-minor):** On peut supprimer le padding-right ici.

2024-03-14 15:31 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.tsx
> +                    {!hideRefreshButton && (
**question (if-minor):** Pourquoi passer par une négation ? Ne serait-ce pas mieux d'appeler la prop `showRefreshButton` ou `displayRefreshButton` ou `withRefresh` et qu'elle soit par défaut à `false` ?

2024-03-14 16:02 UTC, P0ppoff approved these changes

2024-03-15 08:48 UTC, Delmotte-Vincent commented on libs/ui/src/components/RecordEdition/EditRecordPage/EditRecordPage.test.tsx
> +    test('Should hide refresh button on props', async () => {
**nitpick (blocking):** on which props ?

2024-03-15 08:49 UTC, Delmotte-Vincent commented on libs/ui/src/hooks/useGetRecordForm/useGetRecordForm.ts
> +        fetchPolicy: 'no-cache',
**suggestion (non-blocking):** Peut être mettre un todo pour repasser dessus par la suite

2024-03-15 08:50 UTC, Delmotte-Vincent approved these changes

2024-03-15 09:27 UTC, philippechevieux commented on libs/ui/src/hooks/useGetRecordForm/useGetRecordForm.ts
> +        fetchPolicy: 'no-cache',
Note pour moi même: gqlPossibleTypes à importer dans xStream

2024-03-15 10:23 UTC, TdyP approved these changes

2024-03-15 14:28 UTC, merged