feat(ci)/sync-translations-files
leav-solutions/leav-engine pull request #442
Opened 2024-04-03 13:45 UTC by renaudAmsellem

2024-04-03 14:31 UTC, TdyP commented on scripts/compareTranslations.js
> +];
**suggestion (non-blocking):** Possible de détecter automatiquement les fichiers à gérer plutôt qu'une liste en dur? Ou au moins lui passer les dossiers et détecter les différentes langues?

2024-04-03 14:54 UTC, philippechevieux approved these changes

2024-04-03 14:54 UTC, philippechevieux commented
**Question**: Est-ce qu'il y a un ticket pour mettre en place script sur les autres projets ?

2024-04-03 15:58 UTC, P0ppoff requested changes

2024-04-03 15:58 UTC, P0ppoff commented on .github/workflows/ci.yml
> +      - run: sudo apt-get update && sudo apt-get install -y libpoppler-dev libpoppler-cpp-dev libpoppler-private-dev poppler-utils
**question (if-minor):** On pourrait peut être ne pas mettre la ligne car on ne build pas l'application

2024-04-03 15:58 UTC, P0ppoff commented on scripts/compareTranslations.js
> +const translationsPaths = [
**suggestion:** 
```suggestion
const translationsPathsByModule = [
```

2024-04-03 15:58 UTC, P0ppoff commented on scripts/compareTranslations.js
> +    const firstTranslationFile = require(__dirname + '/../' + translationFiles[0]);
**suggestion:** 
```suggestion
    const firstLocaleTranslation = require(__dirname + '/../' + translationFiles[0]);
```

2024-04-03 15:58 UTC, P0ppoff commented on scripts/compareTranslations.js
> +        const nextTranslationFile = require(__dirname + '/../' + translationFiles[translationFileIndex]);
**suggestion:** 
```suggestion
    const [firstLocalePath, ...restLocale] = translationFiles;
    const firstTranslationFile = require(__dirname + '/../' + firstLocalePath);
    for (let translationFileIndex = 0; translationFileIndex < restLocale.length; translationFileIndex++) {
        const nextTranslationFile = require(__dirname + '/../' + restLocale[translationFileIndex]);
```

2024-04-03 15:58 UTC, P0ppoff commented on scripts/compareTranslations.js
> +            translationFiles[0],
**suggestion:** 
```suggestion
            {
                locales: firstTranslationFile,
                errorDisplayName: translationFiles[0],
            }
```

2024-04-03 15:58 UTC, P0ppoff commented on scripts/compareTranslations.js
> +const compareFiles = (file1, fileName1, file2, fileName2, path = []) => {
**praise:** 
```suggestion
const compareFiles = (source, toCheck, path = []) => {
```

2024-04-04 07:49 UTC, renaudAmsellem commented on .github/workflows/ci.yml
> +      - run: sudo apt-get update && sudo apt-get install -y libpoppler-dev libpoppler-cpp-dev libpoppler-private-dev poppler-utils
Ça fonctionne bien sans. (Bémol : à vérifier avec une CI fonctionnelle 😅)

2024-04-04 08:34 UTC, renaudAmsellem commented on scripts/compareTranslations.js
> +];
J'ai passé les dossiers et les langues sont détectés automatiquement.
En revanche, il ne faudrait pas qu'il y ait plusieurs fichiers de trads par dossier.

2024-04-04 10:19 UTC, renaudAmsellem commented on scripts/compareTranslations.js
> +];
Après reflexion, je trouve que la solution de base (liste de fichiers de traduction) a le mérite d'être particulièrement simple.
Elle est très flexible (à condition d'y ajouter les bons noms de fichier).

Les solutions à base de détection de fichiers ont plusieurs défauts :
- Cela complexifie l'algorithme (ajoute `fs` en dépendance, demande de parcourir plusieurs niveaux de dossier / fichiers)
- Ne permet pas de flexibilité : si on veut avoir des fichiers de traductions de cette façon : 
```
- en
  - translations.json
  - shared
    - translations.json
    - autre.json
```

On devra coder un algo assez complexe = plus de bug potentiellement. Alors que la solution simpliste répond à cette problématique en quelques secondes.

Je pense que le KISS s'applique bien dans cette situation.

2024-04-04 14:44 UTC, P0ppoff commented on scripts/compareTranslations.js
> +});
**note:** 
```typescript
const translationsPathsByModule = moduleLocalesPaths.map(moduleLocalePath =>
    fs
        .readdirSync(moduleLocalePath)
        .flatMap(moduleLocale =>
            fs.readdirSync(moduleLocalePath + moduleLocale).map(file => moduleLocalePath + moduleLocale + '/' + file)
        )
);
```

2024-04-05 07:06 UTC, TdyP commented on scripts/compareTranslations.js
> +];
Le code comme il est là où on passe uniquement les dossiers me convient bien. Je pense surtout au cas où on veut gérer de nouvelles langues, ça fera un endroit de moins à (oublier de) modifier

2024-04-05 07:14 UTC, TdyP approved these changes

2024-04-05 07:54 UTC, renaudAmsellem commented on scripts/compareTranslations.js
> +];
**Ok je vais garder l'implémentation où on passe par les dossiers.**


_Ce prochain paragraphe est juste de la discussion_
Ces derniers temps, j'ai récupéré des cartes de bonnes pratiques code / produit.
Notre discussion me fait penser à cette carte : 

![Photo le 05-04-2024 à 09 46](https://github.com/leav-solutions/leav-engine/assets/5941601/ba0a5b6c-a15a-4093-86dc-4966cf178be1)

![Photo le 05-04-2024 à 09 46 #2](https://github.com/leav-solutions/leav-engine/assets/5941601/33fe4a0f-76db-419c-8154-75d56388f4c4)

On commence sans automatisation puis au bout de 3 fois à devoir modifier manuellement, on choisit d'automatiser le process.
J'aime bien cette idée pour optimiser le temps et le code : si quelque chose n'a pas à être automatisé, il ne le sera peut-être jamais. Mais si on y revient souvent alors on l'automatisera.

Peut-être qu'une section dans le README pour ajouter une langue qui mentionne ce fichier est suffisant.

2024-04-05 08:00 UTC, TdyP commented on scripts/compareTranslations.js
> +];
Oui ça se tient comme concept t'as raison :)
Du coup ça te ferait rollback du code que tu as déjà automatisé, ce qui est peut-être un peu dommage
Fais comme tu le sens, les 2 me conviennent

2024-04-05 08:19 UTC, renaudAmsellem commented on scripts/compareTranslations.js
> +];
Je garde l'automatisation 👍

2024-04-05 12:14 UTC, P0ppoff approved these changes

2024-04-05 12:27 UTC, merged