xstream-452/506 adapter le design d'un attribut liaison mono-valuée
leav-solutions/leav-engine pull request #445
Opened 2024-04-04 08:36 UTC by fatb38

2024-04-05 13:13 UTC, fatb38 commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +
pour une raison que j'ignore c'est Prettier qui met l'espace 🤔

2024-04-09 12:25 UTC, renaudAmsellem requested changes

2024-04-09 12:25 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +                selectOptions ? selectOptions.find(option => option.value === activeValue.linkValue.id) : null
**issue (blocking):** Et si la valeur par défaut n'est pas chargé dans la limite des 20 ?

2024-04-09 12:25 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +                selectOptions ? selectOptions.find(option => option.value === activeValue.linkValue.id) : null
**question (blocking):** Pourquoi ne pas être passé par les valeurs initiales de ant ?
cf: libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx:139

Ça permet de laisser ant gérer les values plutôt que de devoir les setter à la mano.

Actuellement, on n'a pas un bon comportement au chargement de page car ant n'a pas la valeur par défaut : 
https://github.com/leav-solutions/leav-engine/assets/5941601/dca4c48b-70a2-40b4-9a27-45252ebf92c5

2024-04-09 12:25 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +            allowClear={!isRequired}
**question (non-blocking):** Pourquoi ne pas faire le même comportement que l'input et le rangepicker ? (permettre le allowclear mais remettre la value au blur)

2024-04-09 12:39 UTC, fatb38 commented on apps/login/package.json
> +    "aristid-ds": "4.0.0-8683c72",
oui très bonne idée de faire un ticket 👍🏻

2024-04-09 13:19 UTC, fatb38 commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +
pareil c'est Prettier qui met une ligne automatiquement 🤷🏻‍♂️

2024-04-09 14:36 UTC, fatb38 commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.test.tsx
> +        const id_value = '11051999';
joyeux anniversaire @Delmotte-Vincent

2024-04-09 15:39 UTC, fatb38 commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.test.tsx
> +                    <MonoValueSelect
🤓 il n'y a pas de Form.Item dans le MonoValueSelect

2024-04-10 12:48 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +export type LinkFieldReducerState = ILinkFieldState<RecordFormElementsValueLinkValue>;
**question:** Est-ce que les exports de `type` / `interface` ne devraient-ils pas être dans des fichiers séparés ?

2024-04-10 12:48 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +                            {state.activeScope === FieldScope.INHERITED && (
**suggestion:** 

Que pensez vous d'un peu de refacto pour faciliter la lecture ?

`const isInherited = state.activeScope === FieldScope.INHERITED;`

```suggestion
                            {isInherited && (
```

2024-04-10 12:48 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +
**question:** Est-ce qu'il ne faudrait pas regarder `res` pour savoir si il est en erreur ?

2024-04-10 13:26 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +    onSelectChange: SubmitValueFunc;
**todo (blocking):** Il faut avoir une cohérence dans les noms
```suggestion
    onSelectClear: DeleteValueFunc;
    onSelectChange: SubmitValueFunc;
```

2024-04-10 13:26 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +    });
**todo:** Le desctructuration est en trop
```suggestion
    const [currentLinkValue, setCurrentLinkValue] = useState<RecordFormElementsValueLinkValue | undefined>(activeValue);
```

2024-04-10 13:26 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +                selectOptions ? selectOptions.find(option => option.value === activeValue.linkValue.id) : null
Elle devrait être renvoyée par l'appel graphQL pour éviter ce genre de soucis

2024-04-10 13:43 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +    }, [recordList]);
memoïzer `selectOptions` et `recordList`

2024-04-11 07:29 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/EditRecordContent.tsx
> +        }
**question:** @TdyP tu peux nous éclairer sur la différence entre les liens simples et avancés dans la création ou l'édition ? 
Notre question est : est ce que les liens simples rentrent dans ce `if` ?

2024-04-12 09:31 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +            allowClear={!isRequired}
On fera ça plus tar si demandé par le produit.

2024-04-12 09:36 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +export type LinkFieldReducerState = ILinkFieldState<RecordFormElementsValueLinkValue>;
J'ai l'impression que de manière générale dans le projet, les types / interfaces sont déclarés dans les fichiers.
En fait je sais pas s'il y a une règle pour ça (les deux façons de faire sont présentes dans leav).

@TdyP tu préfères quoi ?

2024-04-12 09:38 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +                            {state.activeScope === FieldScope.INHERITED && (
C'est du code qu'on a juste déplacé.
Habituellement j'aurais accepté mais pour cette PR de l'enfer, je préfère m'en tenir au "minimum". J'espère que ça te va 😅

2024-04-12 09:39 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect.tsx
> +
On pense avec @P0ppoff que le check de l'erreur doit être fait au niveau du formulaire et pas dans le champ de select.
Si erreur il y a, alors le composant devra recevoir une props en erreur.

C'est pour ça qu'on a modifié le code du composant pour ne pas prendre en compte le retour de la requette à ce moment.

2024-04-12 12:56 UTC, TdyP requested changes

2024-04-12 12:56 UTC, TdyP commented on libs/ui/src/locales/en/shared.json
> +        "product_select": "Select a product"
**nitpick (blocking):** il n'y a pas de notion de "product" dans LEAV. Il faut un terme plus générique
```suggestion
        "record_select": "Select a record"
```

2024-04-12 15:02 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +        if (!onChange) {
On peut le faire tout en haut du composant sinon. Si la fonction n'est pas disponible, on throw une erreur. Qu'en penses tu ?

2024-04-12 15:04 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
> +    return {loading, selectOptions: augmentedSelectOptionsWithActive, updateLeavField};
Un but de ce hook est de gérer le state de recordList sans l'exposer au composant. Et `updateLeavField` a besoin de ces valeurs.

2024-04-17 07:37 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
> +    return {loading, selectOptions: augmentedSelectOptionsWithActive, updateLeavField};
peut-être faudrait-il juste le renommer alors. Là il fait plus que ce qu'il n'y parait à première vue

2024-04-17 07:40 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +        if (!onChange) {
oui éventuellement. Et si on veut juste s'assurer qu'on est bien dans un form antd, peut-on checker que `form` est bien défini plutôt que juste regarde la présence de `onChange` ?

2024-04-17 07:51 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +    const _handleDeleteValue = async (value: IRecordPropertyLink, fetchFreshValues: boolean = true) => {
**question:** A quoi sert le paramètre `fetchFreshValue` ? Je n'ai pas vu d'appel où il est passé à `false`

2024-04-17 07:56 UTC, TdyP approved these changes

2024-04-17 08:14 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +        if (!onChange) {
mmmh, on pourrait avoir `form` défini sans avoir de `onChange` (form = dans un formulaire ant ; `onChange` = descendant direct de `Form.Item`)

2024-04-17 08:15 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
> +    return {loading, selectOptions: augmentedSelectOptionsWithActive, updateLeavField};
`useOptionsQuery` ? car il fait du get et du set finalement

2024-04-17 08:20 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
> +    return {loading, selectOptions: augmentedSelectOptionsWithActive, updateLeavField};
J'ai peut-être mal compris, mais j'ai l'impression qu'il ne s'occupe pas que des options du select, car `updateLeavField` appelle le callback `onSelectChange` qui va trigger le submit.

2024-04-17 08:40 UTC, philippechevieux approved these changes

2024-04-17 12:31 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/useGetOptionsQuery.tsx
> +    return {loading, selectOptions: augmentedSelectOptionsWithActive, updateLeavField};
En fait, c'est un wrapper de `onSelectChange` pour lui donner la valeur "leav" plutôt que la valeur ant

Je n'arrive pas à lui donner un meilleur nom. Si tu as une idée, n'hésite pas :)

2024-04-17 12:35 UTC, renaudAmsellem approved these changes

2024-04-17 12:47 UTC, merged