feat(@leav/ui): implement multivalue select from design system
leav-solutions/leav-engine pull request #455
Opened 2024-04-18 16:04 UTC by renaudAmsellem

2024-04-18 16:20 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +        await form.validateFields([attribute.id]);
**note:** pour faire fonctionner la validation avec le select simple (select mono valué)

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +    infoButton: ReactNode;
**question (non-blocking):** Pourquoi ne pas mettre cette propriété optionnel ? Ca éviterais de la définir à `null` dans les tests

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +            onInfoClick={Boolean(infoButton) ? () => void 0 : undefined}
**question:** Est-ce que tu pourrais expliquer le but de cette ligne ?

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    infoButton: ReactNode;
**question (non-blocking):** Pareil ici ?

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    if (!onChange) {
**question:** Pourquoi la propriété `onChange` est optionnel mais si elle n'est pas présente, `throw` une erreur ?

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +            onDeselect={handleDeselect}
**question:** Est-ce que tu as pu voir avec Lucie pour créer une ticket DS ?

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +            onInfoClick={Boolean(infoButton) ? () => void 0 : undefined}
**question:** Pareil pour cette ligne que dans `MonoValueSelect.tsx`

2024-04-19 07:55 UTC, philippechevieux commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +        }
**suggestion (non-blocking):** Aucune obligation :) 

```suggestion
        const oldValues = Array.isArray(value) ? value : [];
```

2024-04-19 08:40 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MonoValueSelect/MonoValueSelect.tsx
> +            onInfoClick={Boolean(infoButton) ? () => void 0 : undefined}
C'est en attendant de traiter ce ticket : https://aristid.atlassian.net/browse/XSTREAM-551
J'ai écrit le même comportement que sur les composants `DSInputWrapper` et `DSRangePicker`.
Comme - dans le DS - le bouton `infoIcon` n'est affiché que si `onInfoClick` existe, on passe cette propriété avec une fonction qui ne fait rien.

2024-04-19 08:46 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    if (!onChange) {
En fait, comme cette propriété est passée de manière implicite par `Form.Item` si je la déclare en obligatoire, j'ai une erreur dans le `LinkField` (composant qui utilise `MultiValueSelect`).

Je ne vois pas comment faire mieux que ça. Si tu as une idée, je suis preneur.

2024-04-19 08:55 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +        }
vachement mieux en effet :)

2024-04-19 12:02 UTC, TdyP requested changes
Le sujet du ticket était de gérer les valeurs multiples et de se baser sur une liste de valeurs fermée comme source de données. Là on fait encore une recherche sur tous les records de la blbio.
Par exemple, j'ai configuré mon attribute "plateforme de diffusion" avec uniquement "Google" comme valeur possible:
![image](https://github.com/leav-solutions/leav-engine/assets/13244173/81ce1ad7-4e66-4adb-b699-07a1d9b07109)


Dans le formulaire, ça me propose tous les records:
![Capture d’écran du 2024-04-19 13-59-40](https://github.com/leav-solutions/leav-engine/assets/13244173/4d2f2dfd-342c-4af8-9ac3-17ebcc65c36c)

2024-04-19 15:52 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +            onDeselect={handleDeselect}
C'est fait ! https://aristid.atlassian.net/browse/DS-103

2024-04-23 07:28 UTC, philippechevieux approved these changes

2024-04-23 07:52 UTC, TdyP requested changes
Je mets en "request changes" par rapport au bug qui fait que les valeurs ne s'affichent pas à l'ouverture du formulaire d'édition.

2024-04-23 07:52 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/antdUtils.tsx
> +const getinHeritedValue = values => values.find(value => value.isInherited);
**suggestion (non-blocking):** 
```suggestion
const getInheritedValue = values => values.find(value => value.isInherited);
```

2024-04-23 07:52 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/utils.tsx
> +export const mapLeavFieldToAntField = (
**suggestion (non-blocking):** 
```suggestion
export const mapLeavRecordsToAntFieldOptions = (
```

2024-04-23 07:52 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/utils.tsx
> +export const mapAntFieldToLeavField = (
**suggestion (non-blocking):** 
```suggestion
export const mapLeavRecordsToAntFieldOptions = (
```

2024-04-23 12:16 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/utils.tsx
> +export const mapLeavFieldToAntField = (
Je me rends compte que le fichier n'est pas utilisé. donc j'ai tout supprimé 😅

2024-04-23 12:17 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/utils.tsx
> +export const mapAntFieldToLeavField = (
De même ! :)

2024-04-23 12:51 UTC, renaudAmsellem commented
> Je mets en "request changes" par rapport au bug qui fait que les valeurs ne s'affichent pas à l'ouverture du formulaire d'édition.

Ça fonctionne bien en local chez moi :/

2024-04-23 12:57 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/LinkField.tsx
> +    const _infoButton: ReactNode = editRecordState.withInfoButton ? (
**typo:** pas de _

2024-04-23 15:49 UTC, TdyP commented
> > Je mets en "request changes" par rapport au bug qui fait que les valeurs ne s'affichent pas à l'ouverture du formulaire d'édition.
> 
> Ça fonctionne bien en local chez moi :/

Après avoir tout relancé, finalement ça marche bien chez moi aussi

2024-04-23 15:52 UTC, P0ppoff approved these changes

2024-04-23 15:58 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    if (!onChange) {
Finalement, on a créé une interface avec les 2 champs qui viennent d'ant : 

```ts
interface IProvidedByAntFormItem {
    value?: SelectProps<string[]>['value'];
    onChange?: SelectProps['onChange'];
}
```

Puis on étend les props de base avec : 
```ts
interface IMonoValueSelectProps extends IProvidedByAntFormItem {...}
```

2024-04-23 15:58 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    if (!onChange) {
**praise**

2024-04-23 16:06 UTC, merged