fix(@leav/ui): manage display of inherited values in LibraryItemsList
leav-solutions/leav-engine pull request #470
Opened 2024-05-03 13:34 UTC by philippechevieux

## Checklist

Definition Of Review

-   [ ] Own code review done
-   [ ] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] PR was introduced during daily meeting

2024-05-03 14:27 UTC, TdyP requested changes

2024-05-03 14:27 UTC, TdyP commented on apps/core/src/domain/record/recordDomain.ts
> +        const isIStandardValue = (value: IValue): value is IStandardValue => 'raw_value' in value;
**nitpick (blocking):** ce typeguard est déjà défini dans `apps/core/src/utils/typeGuards/index.ts`

2024-05-03 14:27 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +                            return v.value ? v : v.linkValue ?? v.treeValue;
**thought:** je ne comprends pas trop pourquoi on doit faire cette modif et comment ça fonctionne encore, je vais donc faire une revue fonctionnelle :thinking:

2024-05-03 14:28 UTC, TdyP requested changes
Si j'ai une cellule qui n'a pas de valeur du tout, ça plante:
![image](https://github.com/leav-solutions/leav-engine/assets/13244173/5345eea1-7359-482f-b5cd-af1a2f77df7b)

ça semble venir de ce bout de code dans `StandardCell`:
``` 
    const formattedValuesToDisplay = getValuesToDisplay(values)
        .map(valueData => _getValueByFormat(valueData?.value))
        .join(', ');
```

2024-05-03 14:30 UTC, philippechevieux commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +                            return v.value ? v : v.linkValue ?? v.treeValue;
@TdyP Ici je veux retourner l'objet entier `{value: 'ma valeur', isInherited: ...}` et pas seulement la valeur

2024-05-03 14:43 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +                            return v.value ? v : v.linkValue ?? v.treeValue;
Ça fonctionne bien pour les attributs standards, par contre on aura le problème pour les attributs de liaison et arbre. Il faudrait appliquer la même logique dans tous les cas en fait

2024-05-03 14:54 UTC, philippechevieux commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +                            return v.value ? v : v.linkValue ?? v.treeValue;
Je comprend le besoin, par contre je n'aurais pas le temps de le traiter. Je sais pas si quelqu'un pourra le traiter la semaine prochaine ou si on le traite dans un autre ticket ?

2024-05-06 08:58 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +                            return v.value ? v : v.linkValue ?? v.treeValue;
On attend ton retour de congés pour finaliser le ticket :+1:

2024-05-13 14:11 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
**question:** Pourquoi ce -1 ?

2024-05-13 14:11 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/types.ts
> +    linkValue: any;
**nitpick (if-minor):** On pourrait avoir mieux que ce `any` ?

2024-05-13 14:11 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/types.ts
> +    treeValue: any;
**nitpick (if-minor):** idem

2024-05-13 14:13 UTC, philippechevieux commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
@TdyP Initialement on faisait 

```
const [firstValue, ...otherValues] = valuesToDisplay;
...
{otherValues.length ?? 0 ? <AllValuesCount values={valuesToDisplay} attributeType={type} /> : <></>}
```

J'ai repris cette logique, mais peut être que je pourrais sortir ce calcul dans une variable avec un nom plus explicite

2024-05-13 14:31 UTC, TdyP commented
Fonctionnellement ça me semble ok :+1:

2024-05-14 12:33 UTC, TdyP approved these changes

2024-05-14 12:54 UTC, renaudAmsellem commented on libs/ui/src/_queries/records/getRecordsFromLibraryQuery.ts
> +import {AnyPrimitive} from '@leav/utils';
**suggestion:** 
```suggestion
```

2024-05-14 12:57 UTC, renaudAmsellem commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
Pourquoi pas faire un early return aussi : 
```ts
if (valuesToDisplay.length >0) { // Mauvais calcul - juste pour l'exemple
  return <></>
}
return <AllValues .../>
```

2024-05-14 12:59 UTC, renaudAmsellem commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
PS : pour avoir la coloration syntaxique, tu peux écrire le nom du language à côté du "```".
Par ex : "```ts grejnertnh ```"

```ts
import bidule from bidule
```

2024-05-14 15:12 UTC, renaudAmsellem commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/typeGuards.ts
> +        values: SimpleCellValues | LinkCellValues | TreeCellValues | any
**question:** 

```suggestion
        values: SimpleCellValues | LinkCellValues | TreeCellValues
```
Pourquoi `any`?

2024-05-14 15:13 UTC, renaudAmsellem approved these changes

2024-05-15 07:38 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +        setTableColumns(currentColumns => (!isEqual(currentColumns, columns) ? columns : currentColumns));
**question:** C'est ton IDE qui a ajouté ça ? C'est étrange quand même, il ne devrait pas en avoir besoin ?

2024-05-15 07:40 UTC, philippechevieux commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Table.tsx
> +        setTableColumns(currentColumns => (!isEqual(currentColumns, columns) ? columns : currentColumns));
@P0ppoff Oui ça a été ajouté automatiquement

2024-05-15 07:40 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/utils.ts
> +        return values.filter(value => value && !value?.isInherited && value?.value !== null);
**suggestion:** Tu n'as pas besoin de te protéger avec un optional chaining car tu regarde déjà si la valeur est truthy en premier.
```suggestion
        return values.filter(value => value && !value.isInherited && value.value !== null);
```

2024-05-15 08:57 UTC, P0ppoff requested changes

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/StandardCell/StandardCell.tsx
> +        .join(', ');
**question:** Comment on peut se balader avec un `null` dans le code ? le type de retour n'est pas bon dans le fichier utilitaire, le tsconfig est pas très strict du coup et surtout par rapport à avant on ajout un cas sans ajouter vraiment de check sur ce cas de `null`

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/StandardCell/StandardCell.tsx
> +                    return formattedValuesToDisplay;
**suggestion:** On peut inverser ? plus simple à lire
```typescript
                if (isEmpty(formattedValuesToDisplay)) {
                    return formattedValuesToDisplay;
                } else {
                    return <RichTextDisplay displayedValue={formattedValuesToDisplay} />;

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
**polish:** Est ce que l'on peut type le composant comme un composant ?

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +    if (!arrayOfValues.length) {
**suggestion:** 
```suggestion
    if (arrayOfValues.length === 0) {
```

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
Il y a un bug en devenir ici, si valuesToDisplay est `null` alors il ne pourra pas lire `.length`, le nullish coalescing n'est pas au bon endroit

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.tsx
> +                    {valuesToDisplay.length - 1 ?? 0 ? (
ça mériterait une review fonctionnelle

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/AllValuesCount/AllValuesCount.tsx
**polish:** Est ce que l'on peut typer le composant avec une constante et `FunctionComponent` ?

2024-05-15 08:57 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/AllValuesCount/AllValuesCount.tsx
> +        .map(value => {
**question:** Pourquoi ce split en deux ? surtout que le nom n'est pas plus évocateur ?

2024-05-15 08:57 UTC, P0ppoff commented on apps/core/src/domain/indexationManager/indexationManagerDomain.ts
>              if (value === null || (Array.isArray(value) && !value.length)) {
**thought:** Check impossible de la value qui est `null`

2024-05-15 08:57 UTC, P0ppoff commented on apps/core/src/domain/indexationManager/indexationManagerDomain.ts
>              if (value === null || (Array.isArray(value) && !value.length)) {
```suggestion
            if (value.length === 0) {
```

2024-05-15 08:57 UTC, P0ppoff commented on apps/core/src/domain/indexationManager/indexationManagerDomain.ts
>              }
**todo:** Euh, c'est un tableau maintenant, on peut utiliser des méthodes d'une tableau du coup ?

2024-05-15 08:57 UTC, P0ppoff commented on apps/core/src/domain/indexationManager/indexationManagerDomain.ts
>              }
je ne l'ai pas réfléchi mais on peut regarder ensemble comment convertir ça en `map`, `Promise.all` et `reduce`

2024-05-15 09:04 UTC, P0ppoff requested changes

2024-05-15 09:04 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.test.tsx
> +            expect(screen.getByText('record3')).toBeInTheDocument();
**todo:** C'est pas harmonieux avec les autres tests en dessous et surtout ça peut s'écrire mieux je pense. Ce que tu veux tester c'est qu'au même moment tu as deux 
```suggestion
            await waitFor(() => {
                expect(screen.getByText('record2')).toBeVisible();
                expect(screen.getByText('record3')).toBeVisible();
            });
```

2024-05-15 13:23 UTC, P0ppoff approved these changes

2024-05-15 13:23 UTC, merged