Adapt Numeric attribute to Design sysstem
leav-solutions/leav-engine pull request #475
Opened 2024-05-14 12:09 UTC by evoiron

## Checklist

Definition Of Review

-   [ ] Own code review done
-   [ ] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] PR was introduced during daily meeting

2024-05-15 06:58 UTC, P0ppoff commented
Revue fonctionnelle KO 


https://github.com/leav-solutions/leav-engine/assets/10043818/42ada25e-6821-47e6-b614-0c230efcd822

au moment où l'on `clear` le champs on devrait avoir la valeur héritée qui se remet

2024-05-15 07:34 UTC, P0ppoff requested changes
**praise**: Elle est trop bien comme PR, c'est du LEAV est je comprend tout ! trop content aussi de voir que tu as fait ça "simplement" avec les exemples déjà fournis !

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        }
**nitpick:** Il n'y a aucune chance que ce ne soit pas défini
```suggestion
        onChange(valueToSubmit);
```

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +import {KitInputNumberProps} from 'aristid-ds/dist/Kit/DataEntry/InputNumber/types';
**suggestion:** J'aime pas trop les imports depuis `/dist`, pour moi c'est risqué car on se lie à comment l'intérieur de la librairie est structurée. Avec React on peut trouver ce type sans l'écrire : 
```typescript
type KitInputNumberStyledProps = ComponentPropsWithRef<typeof KitInputNumberStyled>['onChange'];
```
Tu peux utiliser ce type directement en inline dans la méthode `_onChange`.

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            await user.click(input);
**question:** Pourquoi cliquer sur l'input avant d'écrire dedans ? 

`type()` fait déjà le clic pour toi : https://testing-library.com/docs/user-event/utility/#type

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            await user.click(input);
**nitpick:** Ici tu ne vide pas le champs, il n'est donc pas vide, ça ne correspond pas à la définition du test. 

Tu voulais pas utiliser `clear()` ?

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +        await user.click(input);
**nitpick:** Pareil ici, je pense que ça marche car la valeur est vide dès le début. D'après la description du test tu devrais `clear()` l'input.

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            expect(helperText).toBeInTheDocument();
**suggestion:** j'ai tendance à utiliser `toBeVisible()` quand c'est possible : https://github.com/testing-library/jest-dom?tab=readme-ov-file#tobevisible

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +    describe('With inheritance', () => {
**todo:** Il te manque les cas d'un input hérité *requis*

2024-05-15 07:34 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            const helperText = screen.getByText(/3.5/);
**question:** Est ce que tu ne chercherais pas plutôt le message du helper : `Inherited value:` ?

2024-05-15 07:47 UTC, TdyP approved these changes

2024-05-15 08:30 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        form.validateFields();
**polish:** ici, et dans le fichier de l'input classique, tu pourrais appeler le `onChange` de Ant qui se charge de faire les deux : `setFieldValue` et `validateFields`.
En plus, il ne validera que le champ en question et pas tout le formulaire comme le ferait `form.validateFields();`

2024-05-16 08:17 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/reducers/standardFieldReducer/standardFieldReducer.ts
> +            newState.isInheritedNotOverrideValue = state.isInheritedValue ? false : state.isInheritedNotOverrideValue;
**note:** mettre directement dans le newstate

2024-05-16 08:52 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/reducers/standardFieldReducer/standardFieldReducer.ts
> +            newState.isInheritedNotOverrideValue = state.isInheritedValue ? false : state.isInheritedNotOverrideValue;
**note:** mettre directement dans le newstate

2024-05-16 08:52 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        if (valueToSubmit === '' && state.inheritedValue) {
**todo:** 
```suggestion
        if (valueToSubmit === '' && state.isInheritedValue) {
```

2024-05-16 08:52 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        if (hasChanged || !state.inheritedValue) {
**todo (if-minor):** 
```suggestion
        if (hasChanged || !state.isInheritedValue) {
```

2024-05-16 08:52 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputWrapper.tsx
> +        if (valueToSubmit === '' && state.inheritedValue) {
**todo (if-minor):** 
```suggestion
        if (valueToSubmit === '' && state.isInheritedValue) {
```

2024-05-16 09:06 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        }
et si ! Il est appelé par StandardFieldValue qui ne lui passe pas de fonction onChange (tout comme il ne le passe pas au DSRangePickerWrapper et au DSInputWrapper

2024-05-16 09:09 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            await user.click(input);
Je suis parti d'un copier/coller des tests de DSInputWrapper qui faisait comme ça

2024-05-16 09:26 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +            const helperText = screen.getByText(/3.5/);
non n'a pas les chaine traduites dans les tests, uniquement les clés et les valeurs. Ici la valeur du champs est différente ("8"), donc pas de confusion possible

2024-05-16 09:38 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.test.tsx
> +        });
il n'y a pas de croix sur les champs number

2024-05-16 09:47 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +};
Par defaut ce champs a cette longueur. A voir avec les UX

2024-05-16 09:49 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/reducers/standardFieldReducer/standardFieldReducer.ts
> +            newState.isInheritedNotOverrideValue = state.isInheritedValue ? false : state.isInheritedNotOverrideValue;
je l'ai fait, il m'a laché une erreur typescript. au final, les deux facons de faire fonctionnnent.

2024-05-16 10:24 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        form.validateFields();
??? quel onChange de Ant ???

2024-05-16 13:01 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        }
Il est passé par <Form.Item /> de Ant.
Il faut faire comme dans les `MonoValueSelect`, `MultiValueSelect`

2024-05-16 13:07 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        form.validateFields();
`<Form.Item />` passe au composant enfant deux props : 
`value` et `onChange`

2024-05-16 13:09 UTC, renaudAmsellem commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        form.validateFields();
Je ne comprends pas pourquoi tu resolve la conversation quand celle-ci n'est pas terminée :o

2024-05-16 13:51 UTC, evoiron commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +        form.validateFields();
au temps pour moi, je te laisse la résoudre alors

2024-05-16 14:27 UTC, evoiron commented
> **praise**: Elle est trop bien comme PR, c'est du LEAV est je comprend tout ! trop content aussi de voir que tu as fait ça "simplement" avec les exemples déjà fournis !

C'est grâce à tout le travail fourni en amont l'équipe qui a bien dégrossi le truc. Merci à eux !

2024-05-16 15:54 UTC, renaudAmsellem approved these changes

2024-05-16 15:54 UTC, renaudAmsellem commented
Top, merci d'avoir pris les retours :)

2024-05-17 07:35 UTC, P0ppoff approved these changes

2024-05-17 07:35 UTC, P0ppoff commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/StandardField/StandardFieldValue/DSInputNumberWrapper.tsx
> +    }
**typo:** 
```suggestion
    if (!onChange) {
        throw Error('DSInputNumberWrapper should be used inside a antd Form.Item');
    }
```

2024-05-17 08:45 UTC, merged