fix: edition modal opens twice
leav-solutions/leav-engine pull request #514
Opened 2024-07-16 12:56 UTC by evoiron

Le problème est dû au fait que la modale d'edition est gérée à la fois par le la ligne du tableau, et par le bouton d'edition dans CellInfos. La correction consiste donc à laisser la gestion de la modale au la ligne du tableau uniquement, et de passer via une prop le handler pour ouvrir la modale au bouton d'action de CellInfos

## Checklist

Definition Of Review

-   [x] Own code review done
-   [x] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-07-16 12:58 UTC, evoiron commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/BodyRow/BodyRow.tsx
**note:** C'est le body row uniquement qui gère la modale d'edition, on passe la fonctoin pour l'ouvrir aux cellules enfants

2024-07-16 13:00 UTC, evoiron commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
**note:** on ne passe plus par le EditRecordBtn, car la modale est gérée par le BodyRow parent

2024-07-17 07:14 UTC, P0ppoff reviewed
J'ai toujours l'erreur en local

2024-07-17 07:15 UTC, P0ppoff requested changes
Il doit y avoir une autre raison

2024-07-17 07:24 UTC, P0ppoff approved these changes

2024-07-17 07:24 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/BodyRow/BodyRow.tsx
> +    const _handleCellInfoEdit = _handleDoubleClick;
**nitpick:** Je n'aurais pas renommer la méthode, pour moi ça n'a aucun apport.

2024-07-17 07:24 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/Cell.test.tsx
> +            render(<Cell columnName="test" data={(mockData as unknown) as ITableCell} onCellInfosEdit={null} />);
**nitpick:** Pourquoi `null` ? il ne doit pas l'être d'après le typage, on pourrait mettre `vi.fn()` ou `() => {}`

2024-07-17 07:24 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.test.tsx
> +                    onEdit={null}
**nitpick:** Même remarque sur la façon de mocker

2024-07-17 07:24 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
> +import {Button} from 'antd';
**question:** Le DS ne permet pas de venir récupérer le bouton de Antd ?

2024-07-17 07:24 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
> +                    aria-label="edit-record"
**question:** @renaudAmsellem est ce que tu sais si c'est utile d'avoir le `aria-label` en plus du `title` donné un peu plus haut ? 
Si oui @evoiron faut que l'internationalise.

2024-07-17 09:05 UTC, evoiron commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
> +                    aria-label="edit-record"
Pour info : le bouton c'est un copier-coller du bouton dans EditRecordBtn

2024-07-17 09:26 UTC, TdyP commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
> +                    aria-label="edit-record"
Je trouve ça un peu dommage de dé-factoriser du code. Ne pouvait-on pas simplement gérer le double-click dans `EditRecordBtn` ou `EditRecordModal` pour éviter qu'il se propage à `BodyRow` ?

2024-07-18 13:53 UTC, evoiron commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/Cell/CellInfos/CellInfos.tsx
> +                    aria-label="edit-record"
J'ai revu ma copie, j'ai déplacé la gestion de la modale dans un provider qui englobe la table. Ainsi, il suffit de faire un useContext dans BodyRow et dans CellInfos pour pouvoir ouvrir la modale, et plus de props passé aux elements enfant.

2024-07-19 08:41 UTC, TdyP approved these changes

2024-07-23 08:06 UTC, P0ppoff approved these changes

2024-07-23 08:06 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/EditRecordModalContext.tsx
> +export default EditRecordModalContext;
**polish:** Habituellement dans les codes que j'ai vu, on exporte directement un hook custom pour récupérer le contexte
```suggestion
export const useEditRecordModalContext = () => useContext(EditRecordModalContext);
```

2024-07-23 08:06 UTC, P0ppoff commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/EditRecordModalContext.tsx
> +const EditRecordModalContext = React.createContext<IEditRecordContextType>({
**polish:** On peut se passer de l'import de `React` ?
```suggestion
const EditRecordModalContext = createContext<IEditRecordContextType>({
```

2024-07-23 08:57 UTC, evoiron commented on libs/ui/src/components/LibraryItemsList/LibraryItemsListTable/EditRecordModalContext.tsx
> +export default EditRecordModalContext;
un hook qui retourne un hook je trouve ça bof

2024-07-23 09:26 UTC, merged