xstream-555 Semantic error: button in a button
leav-solutions/leav-engine pull request #517
Opened 2024-07-17 15:05 UTC by fatb38

## Checklist

Definition Of Review

-   [ ] Own code review done
-   [ ] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-07-18 07:44 UTC, evoiron approved these changes

2024-07-18 10:17 UTC, TdyP requested changes

2024-07-18 10:17 UTC, TdyP commented on libs/ui/src/components/RecordEdition/EditRecordContent/uiElements/LinkField/MultiValueSelect/MultiValueSelect.tsx
> +    fieldValue: IStandardFieldValue;
**question:** Je ne comprends pas trop pourquoi on a besoin de faire passer une `IStandardFieldValue` à travers un `LinkField` juste pour le `useValueDetailsButton` ?

2024-07-18 12:47 UTC, fatb38 commented on apps/portal/src/components/Applications/EditApplicationModal/EditApplicationModal.tsx
> +            background-color: ${dsTheme.general.colors.primary.blue400};
oups erreur 😅

2024-07-18 14:58 UTC, TdyP approved these changes

2024-07-19 08:39 UTC, Delmotte-Vincent approved these changes

2024-07-19 08:40 UTC, merged