feat: use validateRequestToken to regenerate access token if refresh token is valid
leav-solutions/leav-engine pull request #549
Opened 2024-08-27 07:18 UTC by philippechevieux

## Checklist

Definition Of Review

-   [ ] Own code review done
-   [ ] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-08-28 08:42 UTC, philippechevieux commented on apps/core/src/app/auth/authApp.ts
> +            app.post('/auth/login-checker', async (req: IRequestWithContext, res, next) => {
**note:** Au final on a toujours besoin de cette route pour le login

2024-08-29 08:17 UTC, Delmotte-Vincent commented on apps/admin/src/hooks/useRedirectToLogin/useRedirectToLogin.ts
> +const isDevelopmentHelper = () => import.meta.env.DEV;
**suggestion:** 
```suggestion
const isDevEnv = () => import.meta.env.DEV;
```

2024-08-29 08:22 UTC, Delmotte-Vincent commented on apps/core/src/app/auth/authApp.ts
> +    };
**question:** Au lieu de mettre un commentaire est-ce qu'on ne ferait pas une fonction ?

2024-08-29 08:26 UTC, TdyP requested changes

2024-08-29 08:32 UTC, Delmotte-Vincent approved these changes

2024-08-29 08:32 UTC, Delmotte-Vincent commented on apps/core/src/app/auth/authApp.ts
> +                userId = payload.userId;
**suggestion:** 
```suggestion
                const userId = payload.userId
                if (!userId) {
                    throw new AuthenticationError('Invalid accessToken');
                }
```

2024-08-29 08:32 UTC, Delmotte-Vincent commented on apps/core/src/app/helpers/validateRequestToken.spec.ts
> +        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncm91cHNJZCI6WyIxIl0sImlhdCI6MjgyNDc0ODM1MSwiZXhwIjoyODI0NzQ5MjUxfQ.tWTXkdQOoJ79gHi-Yo_ugVoqbmyEGVUK2HYPLhVfvh0';
**praise:** On fera coment en 2059 quand le token sera plus valide ? 😄

2024-08-29 08:32 UTC, Delmotte-Vincent commented on libs/ui/src/hooks/useLoginChecker/useLoginChecker.test.ts
> +        it('Should propagate error from login-checjer call', async () => {
**nitpick (blocking):** 
```suggestion
        it('Should propagate error from login-checker call', async () => {
```

2024-08-29 08:33 UTC, Delmotte-Vincent commented on apps/core/src/app/auth/authApp.ts
> +    const _CheckIfUserExistById = async (userId: string, ctx: IQueryInfos) => {
Si on veut aller plus loin on peut même mettre Exists 😉

2024-08-29 08:36 UTC, philippechevieux commented on apps/core/src/app/auth/authApp.ts
> +        // Everything is ok, we can generate, update and return new tokens
Je l'avais repris du code existant, mais oui maintenant qu'on est dans une fonction on pourrait l'enlever

2024-08-29 08:37 UTC, philippechevieux commented on apps/core/src/app/auth/authApp.ts
> +    };
@Delmotte-Vincent Je pense pas qu'on ai besoin d'une fonction car au final, la suppression se fait une ligne

2024-08-29 08:38 UTC, philippechevieux commented on apps/core/src/app/helpers/validateRequestToken.spec.ts
> +        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncm91cHNJZCI6WyIxIl0sImlhdCI6MjgyNDc0ODM1MSwiZXhwIjoyODI0NzQ5MjUxfQ.tWTXkdQOoJ79gHi-Yo_ugVoqbmyEGVUK2HYPLhVfvh0';
@Delmotte-Vincent On laisserai ChatGPT regénérer un token 😄

2024-08-29 09:21 UTC, philippechevieux commented on apps/core/src/app/auth/authApp.ts
> +    };
A la place, je propose d'enlever le commentaire. Au final on voit bien qu'on sauvegarde une nouvelle session et supprime l'ancienne

2024-08-29 10:03 UTC, TdyP approved these changes

2024-08-29 12:00 UTC, merged