feat(@leav/ui): explorer display Boolean values
leav-solutions/leav-engine pull request #630
Opened 2024-11-25 10:34 UTC by evoiron

## Checklist

Definition Of Review

-   [x] Own code review done (add notes for others)
-   [x] Write message in teams channel
    

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-11-25 13:40 UTC, TdyP approved these changes

2024-11-25 14:55 UTC, TdyP requested changes
le rendu laisse croire que le switchc est clickable et donc la valeur modifiable.
On pourrait le mettre en disabled pour éviter toute confusion
![image](https://github.com/user-attachments/assets/d3a1e4f0-4501-4e0f-a1be-e6a3e66e9909)

2024-11-25 15:29 UTC, evoiron commented
vuavec Cyril et Sebastien, finalement l'affichage se fera sous la forme d'un tag avec les valeurs oui/non (traduites). La couleur sera neutral pour non et primary pour oui : 
<img width="1568" alt="Capture d’écran 2024-11-25 à 16 21 33" src="https://github.com/user-attachments/assets/264d1660-74a7-42be-9c6a-e154c1a5ef7e">

2024-11-25 15:32 UTC, TdyP approved these changes

2024-11-25 17:12 UTC, P0ppoff approved these changes

2024-11-25 17:12 UTC, P0ppoff commented on libs/ui/src/components/Explorer/TableCell.tsx
> +const isBooleanFormatValue = (v: PropertyValueFragment): boolean => v.attribute.format === AttributeFormat.boolean;
**todo:** Je crois que ce n'est pas utilisé. Il faut le supprimer.

2024-11-26 08:27 UTC, evoiron commented on libs/ui/src/components/Explorer/TableCell.tsx
> +const isBooleanFormatValue = (v: PropertyValueFragment): boolean => v.attribute.format === AttributeFormat.boolean;
ah oui j'ai oublié de l'enlever

2024-11-26 08:37 UTC, merged