feat(@leav/ui): add pagination to explorer table
leav-solutions/leav-engine pull request #649
Opened 2024-12-02 13:43 UTC by evoiron

## Checklist

Definition Of Review

-   [x] Own code review done (add notes for others)
-   [ ] Write message in teams channel
    ```
     <Title>

    *️⃣ Impacted projects : Core - DataStudio - Admin - @leav/ui - @leav/utils - ...

    📖 Ticket: https://aristid.atlassian.net/browse/<JIRA_TICKET_IDENTIFIER>

    🧑‍💻 PR: <link to PR/MR>

    ℹ Info: <brief explanation - context - how to test>
    ```

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-12-02 14:16 UTC, TdyP requested changes
Il faut transmettre la pagination au back dans la query et relancer la query dès qu'on change de page

2024-12-03 13:45 UTC, P0ppoff requested changes

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/_queries/useExplorerData.ts
> +    offset = 0
**suggestion:** j'aurais bien aimé garder le même ordre entre la liste ici et la liste qui définit le typage.

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/_queries/explorerQuery.graphql
> +query Explorer($libraryId: ID!, $attributeIds: [ID!]!, $offset: Int, $limit: Int!, $filters: [RecordFilterInput], $multipleSort: [RecordSortInput!]) {
**todo:** Tu n'as pas mis le `$offset` obligatoire alors qu'en vrai tu lui met une valeur par défaut dans le hook `useExplorerData.ts`. Je pense qu'il faut harmoniser.
```suggestion
query Explorer($libraryId: ID!, $attributeIds: [ID!]!, $offset: Int!, $limit: Int!, $filters: [RecordFilterInput], $multipleSort: [RecordSortInput!]) {
```

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +        pageSizeOptions?: number[];
**nitpick:** pas fournis actuellement par l'`<Explorer />`. Je l'aurais soit supprimer des props, soit donner via le composant en dur pour le moment. 

Je pense que la deuxième option est une bonne idée, car au final on voudra peut être que ce soit paramètrable sur la vue.

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +    paginationProps?: {
**nitpick:** pour le moment tu as mis cette props optionnelle, mais est ce que qu'elle l'ai vraiment ? en gros, tu gères le cas de l'utilisateur ne veut pas de pagination, mais sans aller au bout. Pour moi deux possibilités : soit on va au bout de l'option en donnant la main à l'utilisateur sur la pagination soit on laisse ça pour plus tard et pour le moment on met que la pagination est toujours présente.

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +        padding-top: 8px;
**todo:** on passe avec le `general-utilities-spacing-s` ?

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/Explorer.tsx
> +    };
**question:** je me pose la question si c'est la bonne place pour cette méthode, est ce qu'elle ne devrait pas venir du hook des data directement ? ou d'un autre hook ? Il faut en parler de vive voix

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +                          shouldCellUpdate: () => false,
**question:** si pas d'update, on garde pas les références des anciens éléments sur les actions ?

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +                        showTotal={(total, range) => `${range[0]}-${range[1]} of ${total} items`}
**todo:** Comment on fait pour les français ? il faut passer avec i18n.

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +    const containerRef = useRef<HTMLDivElement>(null);
**issue:** j'ai du mal à me dire que typage est bon, si tu initialises à `null`, le typage devrait être
```suggestion
    const containerRef = useRef<HTMLDivElement | null>(null);
```
Comment ça peut fonctionner sans ?

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +    };
**thought:** Est ce que l'on n'extrairait pas tout la logique de la pagination dans un hook ? un peu comme on a fait dans l'`<Explorer />` ?

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +    const onPageSizeChange = (current: number, _pageSize: number) => {
**nitpick:** premier paramètre non utilisé, est ce que l'on sait pourquoi ? est ce que l'on peut lui ajouter un prefix
```suggestion
    const onPageSizeChange = (ignoreCurrentPageSize: number, _pageSize: number) => {
```

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +            ? `${ref.current.clientHeight - getTableHeaderHeight(ref) - 56}px`
**thought:** il faut trouver un moyen de faire transiter le `56` qui me semble être utiliser à la fois dans le CSS et dans le JS ici.

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +    const throttledResize = throttle(entries => {
**todo:** pas de typage de `entries`

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +    const throttledResize = throttle(entries => {
et puis ça veut dire quoi `entries` ?

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +            observer.observe(ref?.current);
**typo:** tu as fait le `if` juste avant.
```suggestion
            observer.observe(ref.current);
```

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +            ref.current?.getBoundingClientRect().top
**typo:** pareil, tu as déjà vérifier `ref.current`
```suggestion
            (ref.current.querySelector('tbody')?.getBoundingClientRect().top ?? 0) -
            ref.current.getBoundingClientRect().top
```

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +const getTableHeaderHeight = ref => {
**todo:** pas de type

2024-12-03 13:45 UTC, P0ppoff commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +const throttle = (func, delay) => {
**todo:** pas de type

2024-12-03 14:25 UTC, evoiron commented on libs/ui/src/components/Explorer/DataView.tsx
> +                          shouldCellUpdate: () => false,
non car les actions prennent des paramètres passés par la table

2024-12-03 14:27 UTC, evoiron commented on libs/ui/src/components/Explorer/DataView.tsx
> +    const onPageSizeChange = (current: number, _pageSize: number) => {
le premier paramètre n'est pas un pageSize mais le numero de page actuel. Mais ok pour le renommer :)

2024-12-03 14:34 UTC, evoiron commented on libs/ui/src/components/Explorer/useTableScrollableHeight.ts
> +    const throttledResize = throttle(entries => {
cf l'api ResizeObserver

2024-12-03 15:32 UTC, P0ppoff commented on libs/ui/src/components/Explorer/DataView.tsx
> +    paginationProps?: {
`noPagination` sera le nom de la props !

2024-12-03 15:34 UTC, P0ppoff commented on libs/ui/src/components/Explorer/Explorer.tsx
> +        refetch({
**todo:** ne pas supprimer les autres variables

2024-12-03 15:34 UTC, P0ppoff commented on libs/ui/src/components/Explorer/Explorer.tsx
> +        refetch({
à vérifier, smell

2024-12-04 13:08 UTC, P0ppoff commented on libs/ui/src/locales/en/shared.json
> +        "pagination-total-number": "{{from}} - {{to}} of {{total}} items"
**todo:** il faut utiliser https://www.i18next.com/translation-function/formatting#number pour avoir les bons séparateurs des milliers

2024-12-04 13:08 UTC, P0ppoff commented on libs/ui/src/locales/fr/shared.json
> +        "pagination-total-number": "{{from}} - {{to}} de {{total}} items"
**typo:** 
```suggestion
        "pagination-total-number": "{{from}} - {{to}} de {{total}} éléments"
```

2024-12-05 10:52 UTC, P0ppoff commented
avant le hook : 
```shell
$ l -h dist              
total 48
drwxr-xr-x  21 p0ppoff  staff   672B  5 déc 11:51 .
drwxr-xr-x@ 17 p0ppoff  staff   544B  5 déc 11:51 ..
drwxr-xr-x   7 p0ppoff  staff   224B  5 déc 11:51 __mocks__
drwxr-xr-x   5 p0ppoff  staff   160B  5 déc 11:51 _gqlTypes
drwxr-xr-x  15 p0ppoff  staff   480B  5 déc 11:51 _queries
drwxr-xr-x  18 p0ppoff  staff   576B  5 déc 11:51 _utils
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:51 antdTheme
drwxr-xr-x  43 p0ppoff  staff   1,3K  5 déc 11:51 components
-rw-r--r--   1 p0ppoff  staff   853B  5 déc 11:51 constants.d.ts
-rw-r--r--   1 p0ppoff  staff   2,1K  5 déc 11:51 constants.js
-rw-r--r--   1 p0ppoff  staff   1,7K  5 déc 11:51 constants.js.map
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:51 contexts
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:51 gqlFragments
drwxr-xr-x   5 p0ppoff  staff   160B  5 déc 11:51 gqlPossibleTypes
drwxr-xr-x  27 p0ppoff  staff   864B  5 déc 11:51 hooks
-rw-r--r--   1 p0ppoff  staff   261B  5 déc 11:51 index.d.ts
-rw-r--r--   1 p0ppoff  staff   489B  5 déc 11:51 index.js
-rw-r--r--   1 p0ppoff  staff   332B  5 déc 11:51 index.js.map
drwxr-xr-x   4 p0ppoff  staff   128B  5 déc 11:51 locales
drwxr-xr-x   7 p0ppoff  staff   224B  5 déc 11:51 testing
drwxr-xr-x  29 p0ppoff  staff   928B  5 déc 11:51 types

```
Après la lib 
```shell
$ l -h dist 
total 48
drwxr-xr-x  21 p0ppoff  staff   672B  5 déc 11:50 .
drwxr-xr-x@ 17 p0ppoff  staff   544B  5 déc 11:50 ..
drwxr-xr-x   7 p0ppoff  staff   224B  5 déc 11:50 __mocks__
drwxr-xr-x   5 p0ppoff  staff   160B  5 déc 11:50 _gqlTypes
drwxr-xr-x  15 p0ppoff  staff   480B  5 déc 11:50 _queries
drwxr-xr-x  18 p0ppoff  staff   576B  5 déc 11:50 _utils
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:50 antdTheme
drwxr-xr-x  43 p0ppoff  staff   1,3K  5 déc 11:50 components
-rw-r--r--   1 p0ppoff  staff   853B  5 déc 11:50 constants.d.ts
-rw-r--r--   1 p0ppoff  staff   2,1K  5 déc 11:50 constants.js
-rw-r--r--   1 p0ppoff  staff   1,7K  5 déc 11:50 constants.js.map
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:50 contexts
drwxr-xr-x   8 p0ppoff  staff   256B  5 déc 11:50 gqlFragments
drwxr-xr-x   5 p0ppoff  staff   160B  5 déc 11:50 gqlPossibleTypes
drwxr-xr-x  27 p0ppoff  staff   864B  5 déc 11:50 hooks
-rw-r--r--   1 p0ppoff  staff   261B  5 déc 11:50 index.d.ts
-rw-r--r--   1 p0ppoff  staff   489B  5 déc 11:50 index.js
-rw-r--r--   1 p0ppoff  staff   332B  5 déc 11:50 index.js.map
drwxr-xr-x   4 p0ppoff  staff   128B  5 déc 11:50 locales
drwxr-xr-x   7 p0ppoff  staff   224B  5 déc 11:50 testing
drwxr-xr-x  29 p0ppoff  staff   928B  5 déc 11:50 types
```

2024-12-05 14:55 UTC, P0ppoff approved these changes

2024-12-06 13:09 UTC, merged