AMP-170 Adding hot reload on dev core image
leav-solutions/leav-engine pull request #650
Opened 2024-12-02 14:17 UTC by fatb38

## Checklist

Definition Of Review

-   [ ] Own code review done (add notes for others)
-   [ ] Write message in teams channel

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-12-02 15:55 UTC, P0ppoff commented on .github/workflows/build_develop.yml
> +      - feature/amp-170-core-hot-reload-in-dev
**note:** Ne pas oublié de le supprimer :)

2024-12-02 15:56 UTC, P0ppoff commented on apps/core/package.json
>          "start:watch": "npm run start:dev",
**todo:** ça serait super de noter quelque part, dans le README, la différence entre les deux.

2024-12-02 15:57 UTC, P0ppoff commented on apps/core/package.json
> +        "watch-dev": "nodemon .",
**question:** Est ce que tu dois tout watch ? genre tous les fichiers dans l'image ou juste un folder en particulier ? je pense aux performances qui pourraient être dégradées si tu observes trop de fichiers.

2024-12-02 15:58 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +RUN yarn add nodemon
**nitpick:** Cette ligne installe tous les paquets et je crois que ce n'est pas ce que l'on veut

2024-12-02 15:58 UTC, P0ppoff approved these changes

2024-12-04 16:15 UTC, fatb38 commented on docker/DOCKERFILES/build/core.dev.Dockerfile
Vu avec les experts Docker de Zenika Grenoble : "surtout ne fais pas ça malheureux" qu'ils m'ont dit 🤣

2024-12-04 16:27 UTC, TdyP commented on docker/DOCKERFILES/build/core.dev.Dockerfile
ok :)
Par curiosité, c'est quoi les risques/trucs pas cool si on fait ça?

2024-12-04 16:36 UTC, fatb38 commented on docker/DOCKERFILES/build/core.dev.Dockerfile
Disons que ça va à l'encontre de la philosophie Docker qui est d'avoir une image qui se comportera toujours de la même manière. Il vaut mieux par exemple passer des variables à l'image et introduire un comportement different dans le code plutôt que d'avoir deux images potentiellement différentes au build.

2024-12-05 08:17 UTC, TdyP commented on docker/DOCKERFILES/build/core.dev.Dockerfile
On peut très bien le gérer de cette manière avec un script exécuté par `CMD` qui lui va voir la variable d'environnement pour lancer en mode watch ou non. Comme ça, on a bien une seule image et un seul Dockerfile qui gère les 2 cas

2024-12-05 08:33 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
On pourrait mais du coup dans les deux cas on a la même image. Il faut pour cela qu'elles aient les mêmes besoins, ce qui n'est peut être pas le cas entre le mode watch qui rebuild de truc à la volée et le mode "prod" qui n'a besoin que des dépendances de run. Je pulsois les 2 images et les 2 Dockerfiles pour le moment, à voir si on peut factoriser après l'écriture.

2024-12-05 08:36 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +# This Dockerfile is meant to build the core of LEAV-Engine.
**suggestion:** à compléter
```suggestion
# This Dockerfile is meant to build the core of LEAV-Engine with a watch on plugin to allow hot reload when plugin changes.
```

2024-12-05 08:38 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +RUN apk --update --no-cache add alpine-sdk perl pkgconfig poppler poppler-dev poppler-utils python3
**todo:** plus besoin de `poppler`, je t'invite à lire la PR : https://github.com/leav-solutions/leav-engine/pull/651 pour savoir quoi laisser comme libs.

2024-12-05 08:41 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +COPY scripts/apps_install.sh ./scripts/apps_install.sh
**polish:** ça serait quand même bien de trier par fréquence de modification
```suggestion
# Copy required files for builds
COPY .yarn ./.yarn
COPY assets/ ./assets
COPY docker/scripts ./scripts
COPY scripts/apps_install.sh ./scripts/apps_install.sh
COPY *.json yarn.lock .yarnrc.yml vite-config-common.js ./
COPY apps/core/package.json ./apps/core/
COPY apps/ ./apps
COPY libs/ ./libs
```
C'est l'ordre de fréquence que j'ai en tête

2024-12-05 08:41 UTC, TdyP commented on docker/DOCKERFILES/build/core.dev.Dockerfile
le watch ne rebuild pas, il fait juste un restart du core, donc les besoins sont les mêmes a priori

2024-12-05 08:46 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +COPY --from=builder /app/apps/core/applications ./apps/core/applications
**nitpick (blocking):** Je ne pense pas que ce soit le bon endroit pour faire ça : le stage s'appelle `prod-dep-install`, que viennent faire les sources buildées de l'application là dedans ? Pour moi c'est à l'étape d'après qu'il faut le mettre, ici on se concentre à mettre en place les bonnes conditions pour le run. D'ailleurs il y a d'autres lignes de `COPY` que l'on peut aussi descendre

2024-12-05 08:46 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +COPY assets/ ./assets
**question:** `assets` est déjà copier pour le build, mais du coup est ce qu'il sert pour le build ? @TdyP as-tu la réponse ?

2024-12-05 08:47 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +FROM node:18-alpine3.18 AS final
**polish:** habituellement en Docker, elle devrait s'appeler
```suggestion
FROM node:18-alpine3.18 AS runner
```

2024-12-05 08:47 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +RUN npm install -g nodemon
**praise:** Je suis fan !!!! mais il faut une version :)

2024-12-05 08:50 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +CMD ["sh", "-c", "/app/scripts/plugins_install.sh && npm run db:migrate && npm run watch-dev"]
**todo (blocking):** Pourquoi d'un coup on passe avec `npm` ? c'est étrange alors que le projet utilise seulement yarn ? alors oui tu l'as supprimer un peu plus tôt mais c'est dommage de ne pas utiliser la même brique tout du long, et puis pareil on ne maitrise pas la version ici, et ça c'est vraiment pas une bonne pratique dans une image de run, tu veux savoir exactement quelle version tu utilises pour que quand tu mettes à jour tu puisse savoir facilement si cette modification qui fait planter l'application.

2024-12-05 08:50 UTC, P0ppoff requested changes
Il reste des petite choses pour que cette image soit parfaite, opérationnelle et puisse servir d'exemple.

2024-12-05 09:33 UTC, fatb38 commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +CMD ["sh", "-c", "/app/scripts/plugins_install.sh && npm run db:migrate && npm run watch-dev"]
le but de supprimer yarn précédemment était de réduire la taille de l'image finale car le cache apportait quasiment 300Mo de données en plus. La pour le run final que ce soit npm ou yarn ça ne change rien, ils se contentent de lancer des scripts. Je ne pense pas qu'il y ait une plus value à remettre la version fixe 4.0.2. On peut tjrs le faire mais ça rajoute du code qui n'est pas indispensable

2024-12-05 09:38 UTC, fatb38 commented on .github/workflows/build_develop.yml
> +                    file: docker/DOCKERFILES/build/core.dev.Dockerfile
Ouaip il est utilisé pour les images taguée en prod. J'attend d'avoir une version finalisée de cette image pour adapter l'autre

2024-12-05 09:43 UTC, fatb38 commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +CMD ["sh", "-c", "/app/scripts/plugins_install.sh && npm run db:migrate && npm run watch-dev"]
ou alors pas défaut l'image contient la v1 de Yarn, elle lance le script tout à fait comme npm ou yarn 4

2024-12-05 14:14 UTC, TdyP commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +COPY assets/ ./assets
à part `leav_engine.png` qui est utilisé dans le README, je me demande si les autres fichiers servent à quelque chose :thinking:

2024-12-06 08:21 UTC, 7Remy approved these changes

2024-12-06 09:43 UTC, P0ppoff commented on .github/workflows/build_develop.yml
> +                    no-cache: true
**question:** maintenant que c'est stable, est ce que ça vaut encore le coup de se passer du cache ?

2024-12-06 09:50 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.dev.Dockerfile
> +COPY scripts/apps_install.sh ./scripts/apps_install.sh
COPY .yarn ./.yarn
COPY assets/ ./assets
COPY docker/scripts ./scripts
COPY scripts/apps_install.sh ./scripts/apps_install.sh
COPY *.json yarn.lock .yarnrc.yml vite-config-common.js ./
COPY apps/ ./apps
COPY apps/core/package.json ./apps/core/ # TODO: util ? 
COPY libs/ ./libs

2024-12-06 09:53 UTC, P0ppoff commented on docker/DOCKERFILES/build/core.Dockerfile
> +COPY apps/core/config ./apps/core/config
**suggestion:** 
```suggestion
COPY docker/scripts ./scripts
COPY apps/core/config ./apps/core/config
COPY --from=prod-dep-install app/ ./
COPY --from=builder /app/apps/core/applications ./apps/core/applications
COPY --from=builder /app/apps/core/dist ./apps/core/dist
```

2024-12-06 10:30 UTC, merged