feat(@leav/ui): select filters in explorer
leav-solutions/leav-engine pull request #654
Opened 2024-12-05 14:22 UTC by evoiron

## Checklist

Definition Of Review

-   [x] Own code review done (add notes for others)
-   [x] Write message in teams channel
    ```
     <Title>

    *️⃣ Impacted projects : Core - DataStudio - Admin - @leav/ui - @leav/utils - ...

    📖 Ticket: https://aristid.atlassian.net/browse/<JIRA_TICKET_IDENTIFIER>

    🧑‍💻 PR: <link to PR/MR>

    ℹ Info: <brief explanation - context - how to test>
    ```

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-12-05 14:26 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +                                                <SimpleFilterDropdown
**note:** J'ai fait ce composant pour montrer comment utiliser le dropdown. Il faudrait paut-etre passer par un composant intermédiaire qui retourne le bon contenu, et plusieurs composants en fonction des differentes dropdown possible

2024-12-05 14:29 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/SimpleFilterDropDown.tsx
> +const ValueListItemValueLi = styled.li`
**note:** J'ai repris ici grossièrement le look n feel des options du KitSelect en mode mutliple

2024-12-05 14:32 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    filter: Array<{
**note:** C'est une première ébauche, il faudra sûrement le faire évoluer en implémentant les différentes dropdown

2024-12-06 08:49 UTC, TdyP requested changes

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    filter: Array<{
**suggestion (blocking):** 
```suggestion
    filters: Array<{
```

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: {field: string};
**issue (blocking):** on pourrait avoir plusieurs filtres sur le même attribut (par exemple, label ne contient pas "2023" et label contient "été"). L'ID du field n'est pas un critère assez discriminant je pense

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: {field: string; operator: string; values: string[]};
**issue (blocking):** idem que pour la suppression

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +        }
**todo (blocking):** il manque les tests pour ces actions

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +`;
**suggestion (non-blocking):** on les utilise à plusieurs endroits, on pourrait les sortir non? On commence même à avoir pas mal de duplications sur le paramétrage de la vue, il serait peut-être temps de factoriser des choses

2024-12-06 08:49 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
**todo (blocking):** il manque les tests pour ce panneau

2024-12-07 15:44 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: {field: string};
Mais est ce que l'on peut dire en clé d'unicité que c'est l'identifiant de l'attribut et le opérateur ?

2024-12-07 15:44 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: {field: string};
sinon on peut ajouter une clé dans la structure avec un identifiant incrémental ?

2024-12-07 15:44 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/open-view-settings/useOpenViewSettings.tsx
> +export const useOpenViewSettings = (library: string, maxFilters: number) => {
**question:** Je suis en train de réfléchir à la gestion de ce paramètre, tu as fait un peu de props drilling. Ce n'est pas un problème en soit et ça fonctionne très bien mais ça me met la puce à l'oreille pour peut être le gérer différemment. Je le mettrais bien dans le contexte, dans la vue. Je pense que ça peut être bien qu'il soit dans le vue car il pourrait être paramètrable depuis l'extérieur. On pourrait aussi le récupérer directement avec le contexte. On pourrait aussi changer un peu la dynamique de gestion de quand on est arrivé au nombre maximum et calculer le `canAddFilter` dans le store directement, et du coup on pourrait dans les actions vérifier que ce paramètre est bon, dans la même veine on pourrait appeler la variable : `hasFilterSlotAvailable` ?

2024-12-07 15:44 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +`;
ah voir si on factorise dès maintenant ou dans un refacto en fin de sprint, même si je pense que durant ce sprint on aura pas le temps.

2024-12-09 11:07 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +`;
Je vais voir à les sortir dans le ticket suivant

2024-12-09 11:22 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: {field: string};
je suis parti sur le combo [id]-[timestamp] comme clé

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/Explorer.tsx
> +        maxFilters: maxFilters ?? defaultViewSettings?.maxFilters ?? viewSettingsInitialState.maxFilters
**todo:** Si c'est dans la vue, c'est dans la vue par defaut directement non ? 
```suggestion
        maxFilters: defaultViewSettings?.maxFilters ?? viewSettingsInitialState.maxFilters
```

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/manage-view-settings.test.tsx
> +        test.only('should be able to toggle filter activation', async () => {
**typo:** On l'a vu :) 
```suggestion
        test('should be able to toggle filter activation', async () => {
```

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts
> +                    id: '',
**nitpick:** Tu dois lui donner l'id ? c'est pas étrange ça ? Je veux dire : je trouve que ce n'est pas le composant qui doit connaitre l'id mais bien le store qui se débrouille.

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts
> +    test(`Action ${ViewSettingsActionTypes.ADD_FILTER} maxfilters test`, () => {
**nitpick (blocking):** C'est deux tests en 1. Tu devrais le séparer car ils sont tous les deux pertinants. Tu as fait un tests pour vérifier que la `canAddFilter` change au bon moment, mais seulement pour l'ajout et pas la suppression, et l'autre test parle que si un action demande un ajout mais que la limite est atteinte bah il se passe rien.

Dans la même veine j'aurais bien regroupé dans des describes
```typescript
describe('adding filters', () => {
   test('can add new filter', () => {});
   test('when limit is reach', () => {});
});
describe('canAddFilter flag', () => {
   test('update to false when ADD_FILTER is called', () => {});
   test('update to true when REMOVE_FILTER is called', () => {});
});
```

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts
> +                // {order: SortOrder.asc, attributeId: 'created_at'}
**todo:** on peut le supprimer ça je crois.

2024-12-09 13:29 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.ts
> +    payload: IExplorerFilter;
**todo:** Je pense pas que la création doit connaitre l'id.
```suggestion
    payload: Omit<IExplorerFilter, 'id'>;
```

2024-12-09 13:32 UTC, evoiron commented on libs/ui/src/components/Explorer/Explorer.tsx
> +        maxFilters: maxFilters ?? defaultViewSettings?.maxFilters ?? viewSettingsInitialState.maxFilters
c'est pas faux

2024-12-09 13:33 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/manage-view-settings.test.tsx
> +        test.only('should be able to toggle filter activation', async () => {
oups

2024-12-09 13:38 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/store-view-settings/viewSettingsReducer.test.ts
> +                    id: '',
dans tous les cas c'est le store qui le calcule et qui. Mais oui j'ai modifié les types pour pas devoir passer un id vide

2024-12-09 15:11 UTC, P0ppoff approved these changes

2024-12-09 16:05 UTC, merged