feat(@leav/ui): explorer text and rich text filter
leav-solutions/leav-engine pull request #662
Opened 2024-12-10 13:24 UTC by evoiron

## Checklist

Definition Of Review

-   [ ] Own code review done (add notes for others)
-   [ ] Write message in teams channel
    ```
     <Title>

    *️⃣ Impacted projects : Core - DataStudio - Admin - @leav/ui - @leav/utils - ...

    📖 Ticket: https://aristid.atlassian.net/browse/<JIRA_TICKET_IDENTIFIER>

    🧑‍💻 PR: <link to PR/MR>

    ℹ Info: <brief explanation - context - how to test>
    ```

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-12-11 15:59 UTC, P0ppoff approved these changes

2024-12-11 15:59 UTC, P0ppoff commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterDropDown.tsx
> +};
on le fera peut être plus tard

2024-12-11 15:59 UTC, P0ppoff commented on libs/ui/src/components/Explorer/display-view-filters/ExplorerFilterBar.tsx
> +                            />
WET before DRY.

2024-12-11 16:40 UTC, TdyP requested changes

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/Explorer.tsx
> +                    <KitEmpty title={t('explorer.empty-data')} />
**praise:** ah vous avez fait le ticket sur la page vide au passage!

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +        const isAttributeAlreadyFiltering = filters.find(filterItem => filterItem.id === attributeOrFilterId);
**nitpick (blocking):** le nom n'est pas adapté, ce n'est pas un booléen et en plus on va lire l'ID dessus juste après

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> -    const _toggleColumnVisibility = (attributeId: string) => () => {
**nitpick (blocking):** le nom `_toggleColumnVisibility` est un vieux copier/coller qui traine n'est-ce pas?

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +                            label: attributeDetailsById[attributeOrFilterId].label,
**nitpick (blocking):** je trouve que le nom `attributeOrFilterId` porte vraiment à confusion. Surtout ici où on l'utilise pour trouver un truc dans `attributeDetailsById`

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterDropDown.tsx
> +export const FilterDropDown: FunctionComponent<{format: AttributeFormat} & IFilterDropDownProps> = ({
**question:** pourquoi recevoir le format en props alors qu'on sur `filter.attribute.format` ?

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterValueList.tsx
> +            }
**suggestion (non-blocking):** 
```suggestion
            onSelectionChanged(multiple ? [...selectedValues, value] : [value]);
```

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/locales/fr/shared.json
> +        "type-a-value": "Écrivez une valeur"
**suggestion:** 
```suggestion
        "type-a-value": "Saisissez une valeur"
```

2024-12-11 16:40 UTC, TdyP commented on libs/ui/src/locales/en/shared.json
> +        "type-a-value": "Type a value"
**thought:** je ne suis pas sur que "type a value" soit très anglais... mais bon il y a sûrement d'autres franglicisme dans ce fichier

2024-12-12 10:28 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/FilterItems.tsx
> +                            label: attributeDetailsById[attributeOrFilterId].label,
Et pourtant il s'agit bien d'un id de filtre ou d'un id d'attribut. Dans ce cas je sépare en 2 fonctions

2024-12-12 10:31 UTC, evoiron commented on libs/ui/src/components/Explorer/manage-view-settings/filter-items/filter-type/FilterDropDown.tsx
> +export const FilterDropDown: FunctionComponent<{format: AttributeFormat} & IFilterDropDownProps> = ({
bonne question, il n'est plus nécessaire en effet :)

2024-12-12 10:35 UTC, evoiron commented on libs/ui/src/locales/en/shared.json
> +        "type-a-value": "Type a value"
Pour le wording, c'est copié/collé du Figma. Normalement c'est au PO de checker ça et de définir le bon wording

2024-12-12 10:44 UTC, TdyP commented on libs/ui/src/locales/en/shared.json
> +        "type-a-value": "Type a value"
il faudra une passe par un vrai anglophone natif surtout, mais c'est pas le sujet de ce ticket, pas de soucis

2024-12-12 15:59 UTC, TdyP requested changes

2024-12-12 15:59 UTC, TdyP commented on libs/ui/src/locales/en/shared.json
> +        "type-a-value": "Type sometthing"
**nitpick (blocking):** Il y a une typo mais je comprends pas trop le changement du coup? pourquoi "something" ?

2024-12-13 13:26 UTC, merged