feat(explorer): allow filters on link attributes
leav-solutions/leav-engine pull request #683
Opened 2024-12-20 11:01 UTC by TdyP

## Checklist

Definition Of Review

-   [x] Own code review done (add notes for others)
-   [ ] Write message in teams channel
    ```
     <Title>

    *️⃣ Impacted projects : Core - DataStudio - Admin - @leav/ui - @leav/utils - ...

    📖 Ticket: https://aristid.atlassian.net/browse/<JIRA_TICKET_IDENTIFIER>

    🧑‍💻 PR: <link to PR/MR>

    ℹ Info: <brief explanation - context - how to test>
    ```

Definition Of Mergeable

-   [ ] 2 approves
-   [ ] 1 functional review - US has been tested
-   [ ] Every comment is handled - blocking ones have been resolved by reviewer
-   [ ] Design OK
-   [ ] Can be tested by POs
-   [ ] PR was introduced during daily meeting

2024-12-20 13:10 UTC, evoiron approved these changes

2024-12-20 13:10 UTC, evoiron commented on libs/ui/src/components/Explorer/_queries/useExplorerData.ts
>      queryFilters = interleaveElement({operator: RecordFilterOperator.AND}, queryFilters);
j'ai fait des modifs dans ce fichiers dans une de mes PR, il va y avoir des conflits, notament avec le interleaveElement

2024-12-20 16:24 UTC, P0ppoff commented on libs/ui/src/components/Explorer/_queries/useExplorerData.ts
> +            value: noValueConditions.includes(condition) ? null : value
**question:** Je ne comprends pas l'ajout de cette ligne, c'est étrange avec le filter au dessus qui élimine les valeurs déjà

2024-12-20 16:25 UTC, P0ppoff requested changes
Il y a un micmac sur le filter

2024-12-24 08:57 UTC, P0ppoff commented on libs/ui/src/components/Explorer/_queries/useExplorerData.ts
> +            value: noValueConditions.includes(condition) ? null : value
Je le supprime car j'ai beau le tourner dans tous les sens je ne vois pas pourquoi c'est là

2024-12-24 08:58 UTC, P0ppoff approved these changes

2024-12-24 09:11 UTC, merged